version: "3.3"

services:
  web:
    build:
      context: .
      dockerfile: ./docker/web.Dockerfile
    ports:
      - ${ServerPort}:${ServerPort}
      - ${DebugPort}:2345
    volumes:
      - .:/clean_web
    env_file: .env
    container_name: boilerplate-web
    depends_on:
      - database

  database:
    image: postgres:14.1-alpine
    environment:
      POSTGRES_USER: ${DBUsername}
      POSTGRES_PASSWORD: ${DBPassword}
      POSTGRES_DATABASE: ${DBName}
    container_name: boilerplate-db
    volumes:
      - psql_data:/var/lib/postgresql/data
  adminer:
    image: adminer
    ports:
      - ${AdminerPort}:8080

volumes:
  psql_data:
    external: true
    name: psql_data
